services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EBripNvRm9L5DKTDfbbJFw  # senha gerada aleatória que eu criei pra você
      POSTGRES_DB: doc_it
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
